### ISSUE TITLE
[Team] 20/04/08

### ISSUE THREAD

**Issue by haveagood** [codesquad-member-2020/todo-3#12]
공통 이슈
- 카드 생성시 RequestBody에 전달해줄 값 논의
- 작성자 데이터 Token화 하여 헤더에 전달

추가
- Json형식 수정 가능성 존재 ( 칸반 전체 호출시 )

**Comment by haveagood** [comment]
[BE]
진행 상황
- 데이터베이스 서버와 백엔드 서버 연결
- 데이터베이스 구조 설계
- 데이터베이스 schema 생성
- 카드 생성 API 설계

목표
- 데이터베이스에 카드 데이터 저장
- 데이터베이스에서 카드 데이터 호출

**Comment by dev-Lena** [comment]
[iOS]
### 어제 한 일
1. Column을 보여주는 각 View의 ViewController 클래스들을 각각 따로 만들었었는데 하나의 ViewController를 재사용할 수 있는 방법이 있지 않을까 찾아봤습니다. 아직 진행중입니다. 

### 오늘 할 일
<img src="https://i.imgur.com/F8Gevt2.png" alt="ToDoDisplay"
	title="ToDoDisplay" width="450" height="300" />
**최대 목표**
- [ ] Container ViewController를 이용한 구조 (하나의 ViewController 클래스 사용)

**최대 목표 달성시 다음 스탭**
- [ ] Container ViewController에 TableView 관련 클래스 
- [ ] Mock데이터 요청 - Alamofire 사용해보기
- [ ] Json 파싱
- [ ] TableView Cell 구성
- [ ] TableView Cell에 데이터 넣기

**Comment by kiyoesjh** [comment]
**어제 한 일**
1. HTML, CSS 작성
2. 개발환경 구성

**오늘 할 일**
- [ ] 스켈레톤 코드 작성
- [ ] 목업 데이터로 렌더링 해보기
- [ ] drag and drop 이벤트 연습하기 & 구현해보기

**Comment by dev-Lena** [comment]
오늘도 다들 고생하셨어요! 저녁 회고때 진행사항 수정해서 업데이트해주시면 더 좋겠습니다! (저도 해야할것같아요 😅) 클로즈하겠습니다!
