### ISSUE TITLE
[Team] 20/04/09

### ISSUE THREAD

**Issue by dev-Lena** [codesquad-member-2020/todo-3#28]
### 팀 공통 이슈
**이번 배포 목표**
1. 기존 데이터 각 컬럼에 표시
2. 카드 추가
3. 새로고침해서 추가된 카드까지 표시
4. 어제 한 일과 오늘 할 일을 코멘트로 남겨주세요!

### 팀 일정
오늘 백엔드 수업이 있다고 해서 회고 스크럼 어제처럼 밤 10시 어떠신가요?

**Comment by sedin2** [comment]
### 어제 한 일
Card 생성
Card 수정
Card 이동
Card 삭제
### 오늘 할 일
JWT, NginX, 코드 리팩토링

**Comment by sedin2** [comment]
> ### 팀 공통 이슈
> **이번 배포 목표**
> 
> 1. 기존 데이터 각 컬럼에 표시
> 2. 카드 추가
> 3. 새로고침해서 추가된 카드까지 표시
> 4. 어제 한 일과 오늘 할 일을 코멘트로 남겨주세요!
> 
> ### 팀 일정
> 오늘 백엔드 수업이 있다고 해서 회고 스크럼 어제처럼 밤 10시 어떠신가요?

10시 좋습니당

**Comment by dev-Lena** [comment]
### 어제 한 일
1. 어떻게 구조를 바꿀지 고민

### 오늘 할 일
* 어제에 이어서 mock 데이터 표시 + 카드 추가
- [ ] Container ViewController를 이용한 구조 (하나의 ViewController 클래스 사용)
  - [x]  Container ViewController에 TableView 관련 클래스
  - [x] Mock데이터 요청
  - [x] Json 파싱
  - [x] TableView Cell 구성
  - [x] TableView Cell에 데이터 넣기

**Comment by kiyoesjh** [comment]
### 어제 한 일
1. 기능 요구 사항 정리
2. 스켈레톤 코드 작성 시작

### 오늘 할 일
- [x] mock 데이터 렌더링
- [ ] 배포 목표에 맞춰 카드 추가, 삭제 등 기능 구현

**Comment by dev-Lena** [comment]
어제도 고생하셨습니다!!
