### ISSUE TITLE
[Team] 20/04/10 Team

### ISSUE THREAD

**Issue by dev-Lena** [codesquad-member-2020/todo-3#44]
### 팀 일정
오늘 4:30분 부터 데모 발표가 있습니다!!

### 팀 공통 이슈
1. 구글 스프레드에 팀 회고 올리기
2. Json 구조 및 key 이름 변경
3. [BE] Delete 기능 수정

**Comment by dev-Lena** [comment]
오늘 데모 정신 없었는데 모두 한 주동안 고생하셨어요! 
한 주동안 감사했습니다! 다음주도 잘 부탁드려요!
저는 조금 더 분발하겠습니다. 화이팅  🎉

**Comment by haveagood** [comment]
다들 고생하셨습니다~~~
푹 쉬시고 다음주에 새로운 마음으로 시작합시다

**Comment by kiyoesjh** [comment]
다들 한 주도 수고 많으셨습니다!
저도 좀 더 분발해보도록 하겠습니다!
다음주도 화이팅!! 👍

**Comment by sedin2** [comment]
다들 고생하셨습니다 !!
다음주부터 새로운 마음으로 시작해요!!

**Comment by dev-Lena** [comment]
### 팀 회고
@haveagood  : 집중을 잘 못한 점이 아쉬웠습니다. 처음부터 스스로의 규칙이나 필요한 사항을 정하고 시작했으면 헷갈리지 않았을텐데 이번주는 이 부분이 좀 아쉬웠습니다. 서비스에 필요한 기능들이 있는데 처음부터 설계를 하면서 순차적으로 진행하는게 아니라 오늘은 이게 끌리네 하면서 잘 안풀리면 다른거 하고 산발적인 개발을 한 것 같습니다. 오늘 데모를 하면서 다른 팀의 스크럼을 관리하는 방법을 봤는데, 깃허브 이슈로 관리하는 것보다 구글 스프레드 시트(엑셀)에 적는 게 좋아보여서 다음주에는 이 방법으로 하는 게 어떤가요? 가능하면 매일 공부 했던거나 새로 알게된 것을 매일 깃허브 wiki에 정리하면 나중에 도움이 되지 않을까합니다. wiki에 각자 공부한거나 새로 알게된 점들을 정리해서 공유하면 좋겠습니다!

@sedin2 : 지난 주에는 다른 팀이랑 할 때보다 나아진 건, 백엔드랑 더 기능적을 나눠서 만든 것이 좋았어요. 전에 했을 때는 모든 기능을 다 같이 페어로 만들었는데 이번에는 분업한 점이 좋았습니다. 그래도 아직 좀 서투른 것 같습니다.😅 기능을 뭘 나눠서 뭘 어떻게 개발할지 좀 어려운 것 같아요. 개발 하다보면 팀끼리 미리 정해놨던 부분을 수정할 때 이 점을 확실하게 슬랙으로 공유하는 등 좀 더 변경 사항을 공유하는데 적극적으로 해야할 것 같습니다. 그래도 지난주 보다 나아진 것 같아서 만족스럽습니다. 할 때 마다 이슈도 만들고 깃헙을 적극적으로 저번주 보다 활용해서 좋았던 것 같습니다.

@kiyoesjh : 저번주 프로젝트에서는 커밋을 많이 남기지 못하고 몰아쳐서 기능 구현을 해가지고 관리가 전혀 안됐던 것 같습니다. 한 브랜치에 모든 기능을 해서 올렸었거든요.😢 이번에는 커밋을 할 때 더 쪼개서 하기 시작했다는 점이 좋았습니다. 저번주보다 이번에 깃과 깃허브 관리가 좀 더 잘 됐던 것 같아요. 저번주에는 페어여서 책임감이 덜했는데 이번에는 혼자라서 책임감이 더 합니다. 초반에는 생각을 많이하다보니까 의욕이 앞서서 한 부분이 있는데 차근차근 단계를 밟아 나가야하는 것이 더 중요하다고 느꼈습니다. 우선순위에 맞게끔 기능 구현하는게 중요한 것 같아요. 팀들이 다들 잘해주셔서 좋았습니다. 슬랙에 깃허브를 구독을 하니까 알림이 오니까 잊지 않고 할 수 있어서 좋았습니다.

@dev-Lena : 저번보다 나아져야한다는 생각 때문에  일단 의욕이 너무 앞섰던 것 같습니다.🥺 이번 프로젝트에서 스스로 세웠던 목표는 '가능하면 문제를 스스로 발견하고 접근해서 해결해보자!' 입니다. 이 목표를 가지고 이번주 프로젝트를 한 주 동안 진행해봤는데 아직 디버깅을 잘 못해서 기능 구현 진도가 생각보다 더 더뎌졌던 것 같습니다. 다음주 목표는 기획서에서 나온 대로 완벽하게 구현하지는 못하더라도 얼추 비슷하게 구현하는게 목표입니다. 팀원분들 모두 친절하시고 다들 천천히 해도 된다고 해주셔서 감사했습니다!
하고싶은 말 : 변경사항이 생기면 문서로 남겨주셨으면 좋겠습니다!

**Comment by dev-Lena** [comment]
한 주동안 감사했습니다! 다음주도 화이팅입니다!
