### ISSUE TITLE
[BE] ResponseBody 샘플 데이터

### ISSUE THREAD

**Issue by haveagood** [codesquad-member-2020/todo-3#5]
# Response Data Sample

1. responseMessage 내부

    1. colName
        - type : String
        - value : 해당 column의 이름
    2. data
        - type : ArrayList
        - value : 각 column에 존재하는 card 데이터

2. data 내부

    1. id
        - type : Int
        - value : 고유 id (데이터베이스에서 지정)
    2. index
        - type : Int
        - value : column에서 해당 card의 위치
    3. title
        - type : String
        - value : 해당 card의 제목
        - iOS에서만 사용, FE에서는 null값을 전달
    4. contents
        - type : String
        - value : card에 작성되는 데이터
    5. writer
        - type : String
        - value : 작성자 데이터

    

    ---

    ## 데이터 예시

    ```
    {
    	"responseMessage" : 
    	[
    		{
    			"colName" : "Todo",
    			"data" : 
    			[
    				{
    					"id" : 1,
    					"index" : 1,
    					"title" : "title1",
    					"contents" : "testData1"
    					"writer" : "todo3"
    				},
    				{
    					"id" : 2,
    					"index" : 2,
    					"title" : "title2"
    					"contents" : "testData2"
    					"writer" : "todo3"
    				}
    			]
    		}
    	]
    }
    ```

**Comment by dev-Lena** [comment]
감사합니다!🙆🏻‍♀️

**Comment by dev-Lena** [comment]
카드의 id는 프론트나 iOS에서 받지 않아도 되지 않을까요??

**Comment by haveagood** [comment]
@dev-Lena 
조금 더 정리해봤습니다!
카드의 id를 받는 이유가 원래, 수정이나 삭제할때, 중복데이터가 존재할 경우 유일한 id값으로 식별하는것이 어떻냐는 제안으로 인해서 추가했던 내용인데, 뭔가 식별할만한 유일한 식별자가 존재하면 삭제해도 될 것 같습니다!!

**Comment by dev-Lena** [comment]
같은 Column 내에서나 Column 간 카드 이동에서 카드의 인덱스 값을 앞단에서 넘겨주면 기존의 DB에서 해당 인덱스에 있는 카드를 찾아서 처리할 수 있지 않나 해서요! 내일 더 얘기해봐요!

**Comment by dev-Lena** [comment]
https://github.com/codesquad-member-2020/todo-3/wiki/API-Documentation
