### ISSUE TITLE
[Team] 20/04/07

### ISSUE THREAD

**Issue by haveagood** [codesquad-member-2020/todo-3#6]
공통 이슈

- Json 형식 맞춰서 백엔드는 mock api 구현, 프론트는 mock api를 활용하여 페이지에 출력

**Comment by haveagood** [comment]
[BE] 목표
- ER 다이어그램 설계, ER 다이어그램 제출
- EC2서버에 데이터베이스 만들기

[BE] 어제까지 진행상황
- sample json데이터 구현
- ER 다이어그램을 통해서 DB 설계

**Comment by kiyoesjh** [comment]
[FE]

✔️ 어제 한일
- 수업
- 구조 고민
- 스켈레톤 코드 작성 시작
- typescript 관련 공부

✔️ 오늘 할일
- 스켈레톤 코드 완성
- typescript 로 변경해보기
- HTML, CSS 시작
- (시간되면) drag and drop event 간단하게 만들어보기

**Comment by dev-Lena** [comment]
[iOS] 
**🙆🏻‍♀️어제 한 일**
1. 스토리보드로 할 수 있는 부분. 각 Column을 표시할 컨테이너 뷰를 만들고 관련 클래스 생성.
2. 컨테이너 뷰에 들어갈 테이블 뷰 및 관련 클래스 생성. -> PR
3. Json 데이터 파싱할 수 있는 클래스와 구조체 생성. -> PR
4. 오토레이아웃 수업

**🧞오늘 할 일**
- [x] Child ViewController 추가 (Segue 사용)
- [ ] 바뀐 Json 구조(?)에 맞게 수정
- [ ] mock 데이터를 성공적으로 받아오는지 확인
- [ ] mock 데이터에 있는 데이터를 각 Column에 표시

**Comment by sedin2** [comment]
[BE]
✔ 어제 한 일
- DDD 수업
- EC2 서버 구축
- EC2에 MySQL 설치

✔ 오늘 할 일
- DB ER다이어그램 같이 설계
- DB Table 작성

**Comment by dev-Lena** [comment]
어제도 고생하셨어요! 클로즈하겠습니다!
